package br.com.fiap.model;

import java.time.LocalDate;

public class Mensagem {
    private long id;
    private String assunto;
    private String destinatario;
    private String remetente;
    private LocalDate data;
    private String conteudo;
    private int status;

    public Mensagem(long id, String assunto, String destinatario, String remetente, LocalDate data, String conteudo, int status) {
        this.id = id;
        this.assunto = assunto;
        this.destinatario = destinatario;
        this.remetente = remetente;
        this.data = data;
        this.conteudo = conteudo;
        this.status = status;
    }

    public Mensagem() {

    }


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAssunto() {
        return assunto;
    }

    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }

    public String getDestinatario() {
        return destinatario;
    }

    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }

    public String getRemetente() {
        return remetente;
    }

    public void setRemetente(String remetente) {
        this.remetente = remetente;
    }

    public LocalDate getData() {
        return data;
    }

    public void setData(LocalDate data) {
        this.data = data;
    }

    public String getConteudo() {
        return conteudo;
    }

    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    public int getStatus() {
        return status;
    }


    public void setStatus(int status) {
        if (status >= 0 && status <= 2) {
            this.status = status;
        } else {
            throw new RuntimeException("Status inválido. Deve ser 0 (não lida), 1 (lida) ou 2 (armazenada).");
        }
    }

    //Comando SQL
    // CREATE TABLE tbl_mensagem (
    //    id number generated by default as identity,
    //    assunto VARCHAR2(255) NOT NULL,
    //    destinatario VARCHAR2(255) NOT NULL,
    //    remetente VARCHAR2(255) NOT NULL,
    //    data DATE NOT NULL,
    //    conteudo varchar2(200),
    //    status NUMBER(1) CHECK (status IN (0, 1, 2)) NOT NULL
    //);


}
